/* TokenOps export engine. Spec section 34 + decisions 0.6, 0.8.
   Customer name warnings fire here (anonymous by default). */

import { fmt, money } from './engine.js';

export function customerNameWarning(state) {
  return state.customerName && state.customerName !== 'Customer A'
    ? `Warning: this export contains the customer name "${state.customerName}". Consider the sanitized version for sharing.`
    : null;
}

export function customerSummaryMarkdown(ctx) {
  const { state, rec, conf, totals, ceiling, be, version, assumptions = [], sources = [] } = ctx;
  const lines = [
    `# TokenOps customer summary`,
    ``,
    `Scenario: ${state.scenarioName}`,
    `Date: ${new Date().toISOString().slice(0, 10)}`,
    ``,
    `## Recommendation`,
    ``,
    rec.headline,
    ...(rec.kind === 'do-not-size' ? ['', 'Missing before sizing:', ...rec.missing.map((m, i) => `${i + 1}. ${m}`)] : []),
    ``,
    `Confidence: ${conf.band}. ${conf.reasons.join(' ')}`,
    ``,
    `## Estimated usage`,
    ``,
    `1. Monthly runs: ${fmt(totals.monthlyRuns)}`,
    `2. Monthly tokens: ${fmt(totals.monthlyTokens)}`,
    `3. Tokens per second (active window): ${fmt(totals.tps)}`,
    ``,
    `## Cost range`,
    ``,
    `1. Provider monthly cost range: ${money(totals.costMin)} to ${money(totals.costMax)}`,
    `2. Cost per run: ${totals.costPerRun ? money(totals.costPerRun, 2) : 'pending'}`,
    ``,
    `## Hardware budget ceiling`,
    ``,
    `1. For owned hardware to beat the token route by ${state.savingsThresholdPercent} percent, the configuration must cost under ${money(ceiling.ceilingCapex)} total (${money(ceiling.ceilingMonthly)} per month over ${state.usefulLifeMonths} months).`,
    `2. Break even volume: about ${be?.result ? fmt(be.result) : 'unknown'} million tokens per month.`,
    ``,
    `## Assumptions`,
    ``,
    ...assumptions.slice(0, 8).map((a, i) => `${i + 1}. ${a.label}: ${a.value}. ${a.reason}`),
    ``,
    `## Risks`,
    ``,
    `1. ${rec.primaryRisk ?? 'Estimates are estimates.'}`,
    ...(rec.missingData ?? []).map((m, i) => `${i + 2}. ${m}`),
    ``,
    `## Next action`,
    ``,
    rec.nextAction,
    ``,
    `## Sources`,
    ``,
    ...sources.slice(0, 12).map((s, i) => `${i + 1}. ${s.label} (reviewed ${s.lastReviewed}): ${s.url}`),
    ``,
    `---`,
    `Rough math for conversations. Never a quote. Generated by calc.nixfred.com/tokenops ${version}.`,
  ];
  return lines.join('\n');
}

export function detailedMathMarkdown(ctx) {
  const { state, traces, rec, conf, rates, hardware, sources, version, weightOverrides } = ctx;
  const out = [
    `# TokenOps detailed math report`,
    ``,
    `Scenario: ${state.scenarioName}`,
    `Date: ${new Date().toISOString().slice(0, 10)}`,
    `Version: ${version}`,
    ``,
    `## Inputs`,
    '```json',
    JSON.stringify(state, null, 2),
    '```',
    ``,
    `## Every formula, every substitution`,
  ];
  for (const t of Object.values(traces)) {
    out.push(``, `### ${t.title}`, ``,
      `1. Answer: ${fmt(t.result)} ${t.resultUnit}`,
      `2. Why it matters: ${t.whyItMatters}`,
      `3. Plain English: ${t.plainEnglish}`,
      `4. Algebra: \`${t.algebra}\``,
      `5. Substitution: \`${t.substitution}\``);
    if (t.variables.length) {
      out.push(``, `| symbol | value | source |`, `| --- | --- | --- |`);
      for (const v of t.variables) out.push(`| ${v.symbol} | ${typeof v.value === 'number' ? fmt(v.value) : v.value} | ${v.source} |`);
    }
    if (t.assumptions.length) out.push(``, ...t.assumptions.map((a, i) => `Assumption ${i + 1}. ${a}`));
    if (t.warnings.length) out.push(``, ...t.warnings.map((w) => `Warning (${w.severity}): ${w.message}`));
  }
  out.push(``, `## Route scores`, ``);
  for (const r of rec.routes ?? []) {
    out.push(`### ${r.label}: ${r.score}/100 (raw ${fmt(r.raw, 1)} of max ${r.max})`);
    for (const c of r.components) out.push(`1. +${fmt(c.points, 1)} ${c.label}`);
    for (const p of r.penalties) out.push(`1. -${fmt(p.points, 1)} ${p.label}`);
    out.push(``);
  }
  if (Object.keys(weightOverrides ?? {}).length) {
    out.push(`## Weight overrides in effect`, '```json', JSON.stringify(weightOverrides, null, 2), '```', ``);
  }
  out.push(`## Confidence`, ``, `${conf.band}: ${conf.substitution}`, ...conf.reasons.map((r, i) => `${i + 1}. ${r}`));
  out.push(``, `## Provider rate table`, ``, `| provider | model | tier | in/M | cached/M | out/M | reviewed |`, `| --- | --- | --- | --- | --- | --- | --- |`);
  for (const r of rates) out.push(`| ${r.providerKey} | ${r.model}${r.userSupplied ? ' (user)' : ''} | ${r.tier} | ${r.inputPerMillion ?? 'n/a'} | ${r.cachedInputPerMillion ?? 'n/a'} | ${r.outputPerMillion ?? 'n/a'} | ${r.lastReviewed ?? ''} |`);
  out.push(``, `## Hardware profiles`, ``);
  for (const h of hardware) out.push(`1. ${h.vendor} ${h.name}: ${h.memoryGB ? h.memoryGB + ' GB' : ''} ${h.memoryType ?? ''} ${h.url}`);
  out.push(``, `## Source registry`, ``);
  sources.forEach((s, i) => out.push(`${i + 1}. ${s.label} (${s.sourceType}, reviewed ${s.lastReviewed}): ${s.url}`));
  out.push(``, `---`, `Rough math for conversations. Never a quote. calc.nixfred.com/tokenops ${version}.`);
  return out.join('\n');
}

export function scenarioJson(state, weightOverrides, version) {
  return JSON.stringify({ tokenops: version, savedAt: new Date().toISOString(), state, weightOverrides }, null, 2);
}

export function sanitizedState(state) {
  return { ...state, customerName: 'Customer A', industry: '', businessProcess: '', scenarioName: 'Scenario', mainDriver: '', mainRisk: '' };
}

export function shareLink(state, weightOverrides) {
  const payload = btoa(unescape(encodeURIComponent(JSON.stringify({ s: state, w: weightOverrides }))));
  return `${location.origin}${location.pathname}?scenario=${payload}`;
}

export function parseShareLink() {
  const p = new URLSearchParams(location.search).get('scenario');
  if (!p) return null;
  try { return JSON.parse(decodeURIComponent(escape(atob(p)))); } catch { return null; }
}

export function download(filename, text, type = 'text/markdown') {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([text], { type }));
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

/* Autosave + named scenarios (decision 0.8.30). */
const AUTO_KEY = 'tokenops-autosave';
const SAVES_KEY = 'tokenops-scenarios';

export const persistence = {
  autosave(state, weightOverrides) {
    try { localStorage.setItem(AUTO_KEY, JSON.stringify({ state, weightOverrides, at: Date.now() })); } catch {}
  },
  loadAutosave() {
    try { return JSON.parse(localStorage.getItem(AUTO_KEY)); } catch { return null; }
  },
  listSaves() {
    try { return Object.keys(JSON.parse(localStorage.getItem(SAVES_KEY) ?? '{}')); } catch { return []; }
  },
  save(name, state, weightOverrides) {
    const all = JSON.parse(localStorage.getItem(SAVES_KEY) ?? '{}');
    all[name] = { state, weightOverrides, at: Date.now() };
    localStorage.setItem(SAVES_KEY, JSON.stringify(all));
  },
  load(name) {
    try { return JSON.parse(localStorage.getItem(SAVES_KEY) ?? '{}')[name]; } catch { return null; }
  },
  clearAll() {
    localStorage.removeItem(AUTO_KEY);
    localStorage.removeItem(SAVES_KEY);
  },
};
