/* TokenOps input field registry. Declarative so Architect Mode renders all
   sections generically and Meeting Mode picks its ~12 with progressive reveal. */

const num = (key, label, opts = {}) => ({ kind: 'number', key, label, ...opts });
const sel = (key, label, choices, opts = {}) => ({ kind: 'select', key, label, choices, ...opts });
const tog = (key, label, opts = {}) => ({ kind: 'toggle', key, label, ...opts });
const lik = (key, label, opts = {}) => ({ kind: 'likert', key, label, ...opts }); // 0-3
const txt = (key, label, opts = {}) => ({ kind: 'text', key, label, ...opts });

export const LIKERT_LABELS = ['none', 'low', 'medium', 'high'];

export const SECTIONS = [
  {
    id: 'context', title: 'Scenario and customer context',
    blurb: 'Controls route scoring and report language. No cost math here.',
    fields: [
      txt('scenarioName', 'Scenario name'),
      txt('customerName', 'Customer name', { hint: 'Defaults to Customer A. Real names trigger export warnings.' }),
      txt('industry', 'Industry'),
      sel('customerSize', 'Customer size', [['smb', 'SMB'], ['mid', 'Mid market'], ['enterprise', 'Enterprise']]),
      txt('businessProcess', 'Primary business process'),
      sel('budgetConfidence', 'Budget confidence', [['unknown', 'Unknown'], ['low', 'Low'], ['medium', 'Medium'], ['high', 'High']]),
      txt('cloudPreference', 'Existing cloud preference', { hint: 'Azure, AWS, Google, none' }),
      txt('mainDriver', 'Main driver'),
      txt('mainRisk', 'Main risk'),
    ],
  },
  {
    id: 'policy', title: 'Data and policy gate',
    blurb: 'A higher private policy score pushes the recommendation toward private execution routes.',
    fields: [
      sel('dataCanLeave', 'Can data leave the customer environment?', [['yes', 'Yes'], ['with-controls', 'With controls'], ['no', 'No']]),
      sel('promptsCanLeave', 'Can prompts leave?', [['yes', 'Yes'], ['no', 'No']]),
      sel('docsCanLeave', 'Can retrieved documents leave?', [['yes', 'Yes'], ['no', 'No']]),
      sel('embeddingsCanLeave', 'Can embeddings leave?', [['yes', 'Yes'], ['no', 'No']]),
      sel('dataSensitivity', 'Data sensitivity', [['low', 'Low'], ['medium', 'Medium'], ['high', 'High']]),
      tog('regulatedData', 'Regulated data present'),
      tog('residencyRequired', 'Data residency required'),
      tog('privateNetworking', 'Private networking required'),
      tog('airGapRequired', 'Air gap required'),
      tog('humanApprovalRequired', 'Human approval required for actions'),
      tog('auditTrailRequired', 'Audit trail required'),
      tog('requiresOnPrem', 'Customer requires on premises'),
      tog('permitsPrivateCloud', 'Customer permits private cloud'),
      tog('permitsPublicCloud', 'Customer permits public cloud'),
      tog('marketplaceBilling', 'Customer requires marketplace billing'),
    ],
  },
  {
    id: 'workloads', title: 'Workload types',
    blurb: 'Quick formulas from the field, plus the deep modern agent path. Turn on what applies.',
    fields: [
      tog('wlModernAgent', 'Modern agent workload (deep path)'),
      tog('wlRag', 'RAG assistant (quick formula)'),
      tog('wlAgents', 'Always-on agents (quick formula)'),
      tog('wlCoding', 'Coding assistant (quick formula)'),
      tog('wlAgenticCoding', 'Agentic coding (quick formula)'),
      num('customWorkloadMonthlyTokens', 'Custom workload tokens per month', { min: 0, step: 1000000 }),
      num('quickInputSharePercent', 'Quick workload input share percent', { min: 0, max: 100, hint: 'Quick-formula tokens are priced at the worker rate using this input/output split.', show: (s) => s.wlRag || s.wlAgents || s.wlCoding || s.wlAgenticCoding || (s.customWorkloadMonthlyTokens ?? 0) > 0 }),
      num('concurrentConnections', 'RAG concurrent connections', { show: (s) => s.wlRag }),
      num('ragDays', 'RAG days per month', { min: 1, max: 31, show: (s) => s.wlRag }),
      num('ragHours', 'RAG hours per day', { min: 1, max: 24, show: (s) => s.wlRag }),
      num('workflows', 'Agentic workflows', { show: (s) => s.wlAgents }),
      num('agDays', 'Agent days per month', { min: 1, max: 31, show: (s) => s.wlAgents }),
      num('agHours', 'Agent hours per day', { min: 1, max: 24, show: (s) => s.wlAgents }),
      num('developers', 'Developers', { show: (s) => s.wlCoding }),
      num('codDays', 'Coding days per month', { min: 1, max: 31, show: (s) => s.wlCoding }),
      num('codHours', 'Coding hours per day', { min: 1, max: 24, show: (s) => s.wlCoding }),
      num('acDevelopers', 'Agentic coding developers', { show: (s) => s.wlAgenticCoding }),
      num('acDays', 'Agentic coding days per month', { min: 1, max: 31, show: (s) => s.wlAgenticCoding }),
      num('acHours', 'Agentic coding hours per day', { min: 1, max: 24, show: (s) => s.wlAgenticCoding }),
    ],
  },
  {
    id: 'volume', title: 'Workload volume', when: (s) => s.wlModernAgent,
    blurb: 'Converts people and habits into monthly runs.',
    fields: [
      num('users', 'Users', { min: 0 }),
      num('concurrentUsers', 'Concurrent users', { min: 0 }),
      num('runsPerUserPerDay', 'Runs per user per day', { min: 0, step: 0.5 }),
      num('activeDaysPerMonth', 'Active days per month', { min: 1, max: 31 }),
      num('activeHoursPerDay', 'Active hours per day', { min: 1, max: 24 }),
      num('adoptionPercent', 'Adoption percent', { min: 0, max: 100 }),
      num('peakConcurrencyFactor', 'Peak concurrency factor', { min: 1, step: 0.5 }),
      num('seasonalityMultiplier', 'Seasonality multiplier', { min: 0.1, step: 0.1 }),
      num('growthPercent', 'Growth percent', { min: 0, max: 500 }),
    ],
  },
  {
    id: 'topology', title: 'Agent topology', when: (s) => s.wlModernAgent,
    blurb: 'Topology multiplies token cost invisibly. This section makes the multiplier visible.',
    fields: [
      sel('topologyType', 'Topology', [
        ['single', 'Single assistant'], ['planner-worker', 'Planner worker'],
        ['planner-worker-judge', 'Planner worker judge'], ['swarm', 'Swarm'],
        ['supervisor', 'Supervisor with specialists'], ['tool-workflow', 'Tool using workflow'],
        ['batch-chain', 'Background batch chain'], ['hitl', 'Human in the loop chain'], ['custom', 'Custom'],
      ]),
      num('plannerCalls', 'Planner calls per run', { min: 0 }),
      num('routerCalls', 'Router calls per run', { min: 0 }),
      num('workerAgents', 'Worker agents per run', { min: 0 }),
      num('workerCallsPerAgent', 'Calls per worker agent', { min: 0 }),
      num('judgeCalls', 'Judge calls per run', { min: 0 }),
      num('criticCalls', 'Critic calls per run', { min: 0 }),
      num('summarizerCalls', 'Summarizer calls per run', { min: 0 }),
      num('memoryReadCalls', 'Memory read calls per run', { min: 0 }),
      num('memoryWriteCalls', 'Memory write calls per run', { min: 0 }),
      num('ragCallsPerRun', 'RAG calls per run', { min: 0 }),
      num('toolPlanningCalls', 'Tool planning calls per run', { min: 0 }),
      num('toolResultSummaryCalls', 'Tool result summary calls per run', { min: 0 }),
      num('retryRatePercent', 'Retry rate percent', { min: 0, max: 100 }),
      num('replanRatePercent', 'Replan rate percent', { min: 0, max: 100 }),
      num('escalationPercent', 'Escalation to premium model percent', { min: 0, max: 100 }),
      num('maxLoopDepth', 'Max loop depth', { min: 1 }),
    ],
  },
  {
    id: 'anatomy', title: 'Token anatomy per role', when: (s) => s.wlModernAgent,
    blurb: 'What one call of each role costs in tokens. Roles with zero calls are ignored.',
    fields: [
      num('roles.planner.inputTokensPerCall', 'Planner input tokens per call', { min: 0 }),
      num('roles.planner.outputTokensPerCall', 'Planner output tokens per call', { min: 0 }),
      num('roles.worker.inputTokensPerCall', 'Worker input tokens per call', { min: 0 }),
      num('roles.worker.outputTokensPerCall', 'Worker output tokens per call', { min: 0 }),
      num('roles.judge.inputTokensPerCall', 'Judge input tokens per call', { min: 0 }),
      num('roles.judge.outputTokensPerCall', 'Judge output tokens per call', { min: 0 }),
      num('roles.summarizer.inputTokensPerCall', 'Summarizer input tokens per call', { min: 0, show: (s) => s.summarizerCalls > 0 }),
      num('roles.summarizer.outputTokensPerCall', 'Summarizer output tokens per call', { min: 0, show: (s) => s.summarizerCalls > 0 }),
      num('roles.router.inputTokensPerCall', 'Router input tokens per call', { min: 0, show: (s) => s.routerCalls > 0 }),
      num('roles.router.outputTokensPerCall', 'Router output tokens per call', { min: 0, show: (s) => s.routerCalls > 0 }),
      num('roles.critic.inputTokensPerCall', 'Critic input tokens per call', { min: 0, show: (s) => s.criticCalls > 0 }),
      num('roles.critic.outputTokensPerCall', 'Critic output tokens per call', { min: 0, show: (s) => s.criticCalls > 0 }),
      num('cachedInputPercent', 'Cached input percent', { min: 0, max: 100 }),
      num('batchEligiblePercent', 'Batch eligible percent', { min: 0, max: 100 }),
    ],
  },
  {
    id: 'snowball', title: 'Context snowball', when: (s) => s.wlModernAgent,
    blurb: 'Agents that carry prior work forward quietly multiply input cost.',
    fields: [
      tog('carryEnabled', 'Carry forward previous step context'),
      num('carryForwardPercent', 'Carry forward percent', { min: 0, max: 100, show: (s) => s.carryEnabled }),
      num('priorStepInputTokens', 'Average prior step input tokens', { min: 0, show: (s) => s.carryEnabled }),
      num('priorStepOutputTokens', 'Average prior step output tokens', { min: 0, show: (s) => s.carryEnabled }),
      num('carriedSteps', 'Number of carried steps', { min: 0, show: (s) => s.carryEnabled }),
      tog('summarizeCarry', 'Summarize previous steps before carry', { show: (s) => s.carryEnabled }),
      num('summaryCompressionRatio', 'Summary compression ratio', { min: 0.01, max: 1, step: 0.05, show: (s) => s.carryEnabled && s.summarizeCarry }),
    ],
  },
  {
    id: 'rag', title: 'RAG and retrieval',
    blurb: 'Retrieved context is usually the biggest single input line item.',
    fields: [
      tog('ragEnabled', 'RAG enabled'),
      txt('vectorStoreProvider', 'Vector store provider', { show: (s) => s.ragEnabled }),
      num('documentsIndexed', 'Documents indexed', { min: 0, show: (s) => s.ragEnabled }),
      num('avgDocPages', 'Average pages per document', { min: 1, show: (s) => s.ragEnabled }),
      num('tokensPerPage', 'Average tokens per page', { min: 1, show: (s) => s.ragEnabled }),
      num('chunkSize', 'Chunk size (tokens)', { min: 64, show: (s) => s.ragEnabled }),
      num('chunkOverlap', 'Chunk overlap (tokens)', { min: 0, show: (s) => s.ragEnabled }),
      num('chunksRetrievedPerQuery', 'Chunks retrieved per query', { min: 0, show: (s) => s.ragEnabled }),
      num('avgTokensPerChunk', 'Average tokens per retrieved chunk', { min: 0, show: (s) => s.ragEnabled }),
      tog('rerankerEnabled', 'Reranker enabled', { show: (s) => s.ragEnabled }),
      num('dailyNewDocuments', 'Daily new documents', { min: 0, show: (s) => s.ragEnabled }),
      num('dailyChangedDocuments', 'Daily changed documents', { min: 0, show: (s) => s.ragEnabled }),
      num('embeddingPricePerMillion', 'Embedding price per million tokens (USD)', { min: 0, step: 0.01, show: (s) => s.ragEnabled, hint: 'User supplied. Public defaults vary by model.' }),
    ],
  },
  {
    id: 'tools', title: 'Tools and external systems',
    blurb: 'Large tool schemas and raw tool outputs can become major cost drivers.',
    fields: [
      tog('toolUseEnabled', 'Tool use enabled'),
      num('toolsExposed', 'Tools exposed', { min: 0, show: (s) => s.toolUseEnabled }),
      num('avgToolSchemaTokens', 'Average schema tokens per tool', { min: 0, show: (s) => s.toolUseEnabled }),
      num('toolCallsPerRun', 'Tool calls per run', { min: 0, show: (s) => s.toolUseEnabled }),
      num('avgToolResultTokens', 'Average tool result tokens', { min: 0, show: (s) => s.toolUseEnabled }),
      tog('toolResultSummarization', 'Summarize tool results', { show: (s) => s.toolUseEnabled }),
      num('toolResultSummaryTokens', 'Summary tokens per result', { min: 0, show: (s) => s.toolUseEnabled && s.toolResultSummarization }),
      num('failedToolRatePercent', 'Failed tool call rate percent', { min: 0, max: 100, show: (s) => s.toolUseEnabled }),
    ],
  },
  {
    id: 'memory', title: 'Memory and audit history',
    blurb: 'Memory recall adds input cost; audit retention turns tokens into disk.',
    fields: [
      tog('memoryEnabled', 'Memory enabled'),
      num('memRetrievalsPerRun', 'Memory retrievals per run', { min: 0, show: (s) => s.memoryEnabled }),
      num('memChunksRetrieved', 'Memory chunks retrieved', { min: 0, show: (s) => s.memoryEnabled }),
      num('memChunkTokens', 'Tokens per memory chunk', { min: 0, show: (s) => s.memoryEnabled }),
      num('memWritesPerRun', 'Memory writes per run', { min: 0, show: (s) => s.memoryEnabled }),
      num('memWriteSummaryTokens', 'Summary tokens per write', { min: 0, show: (s) => s.memoryEnabled }),
      tog('traceRetained', 'Session traces retained'),
      num('traceRetentionDays', 'Trace retention days', { min: 0, show: (s) => s.traceRetained }),
      num('avgBytesPerTokenInTrace', 'Bytes per token in trace', { min: 1, show: (s) => s.traceRetained }),
    ],
  },
  {
    id: 'routing', title: 'Model routing', when: (s) => s.wlModernAgent,
    blurb: 'Different roles deserve different models. This is where agent economics get won.',
    fields: [
      sel('roles.planner.provider', 'Planner provider', 'PROVIDERS'),
      sel('roles.planner.tier', 'Planner tier', 'TIERS'),
      sel('roles.worker.provider', 'Worker provider', 'PROVIDERS'),
      sel('roles.worker.tier', 'Worker tier', 'TIERS'),
      sel('roles.judge.provider', 'Judge provider', 'PROVIDERS'),
      sel('roles.judge.tier', 'Judge tier', 'TIERS'),
      sel('roles.summarizer.provider', 'Summarizer provider', 'PROVIDERS', { show: (s) => s.summarizerCalls > 0 }),
      sel('roles.summarizer.tier', 'Summarizer tier', 'TIERS', { show: (s) => s.summarizerCalls > 0 }),
    ],
  },
  {
    id: 'sizing', title: 'Private inference sizing',
    blurb: 'Memory fit and throughput fit are separate gates. The bigger one wins.',
    fields: [
      sel('modelSizeQuickPick', 'Model size quick pick', [
        ['', 'custom'], ['8', '8B'], ['13', '13B'], ['30', '30B'], ['47', '8x7B (about 47B total)'], ['70', '70B'], ['120', '120B'], ['405', '405B'],
      ], { hint: 'Sets the parameter count below. The spec model rows, one click each.' }),
      num('modelParamsB', 'Model parameters (billions)', { min: 0.5, step: 0.5 }),
      sel('quantization', 'Quantization', [['fp16', 'FP16 / BF16 (2 B/param)'], ['fp8', 'FP8 (1 B/param)'], ['int8', 'INT8 (1 B/param)'], ['int4', 'INT4 (0.5 B/param)']]),
      num('modelInstances', 'Model instances', { min: 1 }),
      sel('gpuChoice', 'GPU candidate', 'HARDWARE'),
      num('concurrentSequences', 'Concurrent sequences', { min: 1 }),
      num('contextLengthTokens', 'Context length (tokens)', { min: 512, step: 1024 }),
      num('kvLayers', 'Model layers', { min: 1 }),
      num('kvHeads', 'KV heads', { min: 1 }),
      num('kvHeadDim', 'Head dimension', { min: 16 }),
      num('kvBytesPerElement', 'KV bytes per element', { min: 0.5, step: 0.5 }),
      num('runtimeOverheadPercent', 'Runtime overhead percent', { min: 0, max: 100 }),
      num('safetyMarginPercent', 'Safety margin percent', { min: 0, max: 100 }),
      num('gpuMemoryUtilizationTarget', 'GPU memory utilization target', { min: 0.1, max: 1, step: 0.05 }),
      num('targetGpuUtilization', 'Target GPU utilization', { min: 0.1, max: 1, step: 0.05 }),
      num('userBenchmarkTpsPerGpu', 'Measured benchmark TPS per GPU (overrides estimate)', { min: 0, hint: 'Leave blank to use the labeled estimate.' }),
      num('targetCompletionSeconds', 'Target completion seconds', { min: 1 }),
      num('minimumPlatformGpuCount', 'Minimum platform GPU count', { min: 0 }),
    ],
  },
  {
    id: 'storage', title: 'Storage', blurb: 'Raw capacity is never what gets bought.',
    fields: [
      num('modelRepoTB', 'Model repository TB', { min: 0, step: 0.5 }),
      num('retentionMonths', 'Retention months', { min: 1 }),
      num('storageGrowthPercent', 'Growth percent', { min: 0, max: 500 }),
      num('replicationFactor', 'Replication factor', { min: 1, step: 0.5 }),
      num('backupFactor', 'Backup factor', { min: 1, step: 0.1 }),
    ],
  },
  {
    id: 'network', title: 'Network', blurb: 'Application traffic sizes the front side. Backend fabric is rule based.',
    fields: [
      num('avgBytesPerToken', 'Average bytes per token', { min: 1 }),
      num('avgRetrievedBytesPerQuery', 'Retrieved bytes per RAG query', { min: 0, show: (s) => s.ragEnabled }),
      num('avgToolPayloadBytes', 'Tool payload bytes per call', { min: 0, show: (s) => s.toolUseEnabled }),
      num('networkOverheadMbps', 'Overhead Mbps', { min: 0 }),
    ],
  },
  {
    id: 'economics', title: 'Economics and the ceiling',
    blurb: 'TokenOps never prices hardware. It tells you what the hardware has to cost.',
    fields: [
      sel('ceilingBaseline', 'Ceiling baseline', [['cheapest', 'Cheapest provider total'], ['selected', 'Selected role routing total']]),
      num('savingsThresholdPercent', 'Required savings threshold percent', { min: 0, max: 90 }),
      num('usefulLifeMonths', 'Useful life months', { min: 1 }),
      num('gpuQuote', 'Hardware quote (USD, optional)', { min: 0, step: 1000, hint: 'Enter a real quote for an instant under or over verdict.' }),
      num('rentedGpuHourly', 'Rented GPU hourly price (USD, optional)', { min: 0, step: 0.25 }),
      num('rentedGpuCount', 'Rented GPU count', { min: 1, show: (s) => s.rentedGpuHourly != null && s.rentedGpuHourly !== '' }),
      num('rentedActiveHoursPerMonth', 'Rented active hours per month', { min: 0, show: (s) => s.rentedGpuHourly != null && s.rentedGpuHourly !== '' }),
    ],
  },
  {
    id: 'needs', title: 'Route drivers',
    blurb: 'What the customer actually needs. These drive the route scores; every weight is visible in the scoring panel.',
    fields: [
      lik('needTimeToValue', 'Time to value need'),
      lik('needQuality', 'Model quality need'),
      lik('needLowOps', 'Low operations burden need'),
      sel('usagePattern', 'Usage pattern', [['bursty', 'Bursty'], ['steady', 'Steady']]),
      lik('needGovernance', 'Governance need'),
      lik('needAgentBuilder', 'Agent builder need'),
      lik('needIntegration', 'Integration need'),
      lik('needModelRouting', 'Model routing need'),
      lik('needAudit', 'Audit need'),
      lik('needBusinessUserCreation', 'Business user agent creation'),
      lik('needDataGravity', 'Data gravity'),
      lik('needOntology', 'Ontology driven context'),
      lik('needInternalApis', 'Internal API need'),
      lik('needEnterpriseRetrieval', 'Enterprise retrieval need'),
      lik('readinessGap', 'AI readiness gap'),
      lik('useCaseAmbiguity', 'Use case ambiguity'),
      lik('needVendorSelection', 'Vendor selection need'),
      lik('integrationComplexity', 'Integration complexity'),
      lik('needGovernancePlanning', 'Governance planning need'),
      lik('opsReadiness', 'Operational readiness to own hardware'),
      lik('hpePreference', 'HPE platform preference'),
      lik('nvidiaPreference', 'NVIDIA preference'),
      lik('amdPreference', 'AMD preference'),
      sel('usageConfidence', 'Usage confidence', [['estimated', 'Estimated'], ['measured', 'Measured from telemetry']]),
      sel('tokenEstimateConfidence', 'Token estimate confidence', [['estimated', 'Estimated'], ['measured', 'Measured']]),
      sel('modelQualityConfidence', 'Model quality confidence', [['low', 'Low'], ['medium', 'Medium'], ['high', 'High']]),
      sel('opsReadinessConfidence', 'Ops readiness confidence', [['low', 'Low'], ['medium', 'Medium'], ['high', 'High']]),
    ],
  },
];

/* Meeting Mode wizard: ~12 core inputs with progressive reveal (decision 0.5.22). */
export const MEETING_STEPS = [
  {
    id: 'm-usecase', title: 'The use case',
    fields: [
      txt('scenarioName', 'What are we sizing?'),
      sel('customerSize', 'Customer size', [['smb', 'SMB'], ['mid', 'Mid market'], ['enterprise', 'Enterprise']]),
      sel('budgetConfidence', 'Budget signal', [['unknown', 'Unknown'], ['low', 'Weak'], ['medium', 'Some budget'], ['high', 'Committed']]),
    ],
  },
  {
    id: 'm-scale', title: 'Scale',
    fields: [
      num('users', 'Users'),
      num('runsPerUserPerDay', 'Runs per user per day', { step: 0.5 }),
      num('adoptionPercent', 'Adoption percent', { min: 0, max: 100 }),
      num('activeDaysPerMonth', 'Active days per month', { min: 1, max: 31, reveal: (s) => s.users > 0 }),
    ],
  },
  {
    id: 'm-policy', title: 'Policy gate',
    fields: [
      sel('dataCanLeave', 'Can data leave the environment?', [['yes', 'Yes'], ['with-controls', 'With controls'], ['no', 'No']]),
      tog('regulatedData', 'Regulated data present', { reveal: (s) => s.dataCanLeave && s.dataCanLeave !== 'yes' }),
      tog('requiresOnPrem', 'Must run on premises', { reveal: (s) => s.dataCanLeave === 'no' }),
    ],
  },
  {
    id: 'm-shape', title: 'Workload shape',
    fields: [
      sel('topologyType', 'Agent shape', [
        ['single', 'Single assistant'],
        ['planner-worker', 'Planner and workers'],
        ['planner-worker-judge', 'Planner, workers, judge'],
        ['swarm', 'Swarm'],
      ]),
      num('cachedInputPercent', 'Prompt cache hit percent', { min: 0, max: 100 }),
      num('retryRatePercent', 'Retry rate percent', { min: 0, max: 100, reveal: (s) => s.topologyType !== 'single' }),
    ],
  },
];

/* Topology presets patch call counts when the shape changes. */
export const TOPOLOGY_PRESETS = {
  'single': { plannerCalls: 0, routerCalls: 0, workerAgents: 1, workerCallsPerAgent: 1, judgeCalls: 0, criticCalls: 0, summarizerCalls: 0 },
  'planner-worker': { plannerCalls: 1, routerCalls: 0, workerAgents: 2, workerCallsPerAgent: 2, judgeCalls: 0, criticCalls: 0, summarizerCalls: 1 },
  'planner-worker-judge': { plannerCalls: 1, routerCalls: 0, workerAgents: 2, workerCallsPerAgent: 2, judgeCalls: 1, criticCalls: 0, summarizerCalls: 1 },
  'swarm': { plannerCalls: 1, routerCalls: 1, workerAgents: 6, workerCallsPerAgent: 3, judgeCalls: 1, criticCalls: 1, summarizerCalls: 2 },
  'supervisor': { plannerCalls: 1, routerCalls: 1, workerAgents: 3, workerCallsPerAgent: 2, judgeCalls: 1, criticCalls: 0, summarizerCalls: 1 },
  'tool-workflow': { plannerCalls: 1, routerCalls: 0, workerAgents: 1, workerCallsPerAgent: 3, judgeCalls: 0, criticCalls: 0, summarizerCalls: 1, toolPlanningCalls: 2, toolResultSummaryCalls: 2 },
  'batch-chain': { plannerCalls: 1, routerCalls: 0, workerAgents: 4, workerCallsPerAgent: 1, judgeCalls: 0, criticCalls: 0, summarizerCalls: 1 },
  'hitl': { plannerCalls: 1, routerCalls: 0, workerAgents: 1, workerCallsPerAgent: 2, judgeCalls: 1, criticCalls: 0, summarizerCalls: 1 },
};

/* Workload presets per spec 44.5. Each patches state on top of defaults. */
export const WORKLOAD_PRESETS = {
  'support-pilot': { label: 'Customer support agent pilot', patch: {} },
  'rag-assistant': { label: 'Simple RAG assistant', patch: { topologyType: 'single', ...TOPOLOGY_PRESETS['single'], ragEnabled: true, ragCallsPerRun: 1, users: 100, runsPerUserPerDay: 8, adoptionPercent: 60 } },
  'sales-assistant': { label: 'Sales assistant', patch: { topologyType: 'planner-worker', ...TOPOLOGY_PRESETS['planner-worker'], users: 50, runsPerUserPerDay: 10, adoptionPercent: 70 } },
  'doc-processing': { label: 'Document processing agent', patch: { topologyType: 'batch-chain', ...TOPOLOGY_PRESETS['batch-chain'], users: 20, runsPerUserPerDay: 40, adoptionPercent: 100, usagePattern: 'steady' } },
  'coding-assistant': { label: 'Coding assistant', patch: { wlModernAgent: false, wlCoding: true } },
  'agentic-swarm': { label: 'Agentic coding swarm', patch: { wlModernAgent: false, wlAgenticCoding: true } },
  'regulated-private': { label: 'Private regulated assistant', patch: { dataCanLeave: 'no', regulatedData: true, residencyRequired: true, requiresOnPrem: true, dataSensitivity: 'high', needDataGravity: 3, needEnterpriseRetrieval: 2 } },
  'batch-volume': { label: 'High volume background batch', patch: { topologyType: 'batch-chain', ...TOPOLOGY_PRESETS['batch-chain'], users: 5, runsPerUserPerDay: 500, adoptionPercent: 100, usagePattern: 'steady', batchEligiblePercent: 80 } },
};
